version: '3.1'

services:
  mongo:
    image: mongo:7.0.0-jammy
    restart: always
    ports:
      - ${mongodb_port}:${mongodb_port}
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongodb_username}
      MONGO_INITDB_ROOT_PASSWORD: ${mongodb_password}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${mongodb_username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${mongodb_password}
      ME_CONFIG_MONGODB_URL: mongodb://${mongodb_username}:${mongodb_password}@mongo:${mongodb_port}/
